[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "sqdtoolz"
version = "0.9.1.dev1"
description = "toolbox to control and run experiments"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Prasanna Pakkiam", email = "p.pakkiam@uq.edu.au" },
    { name = "Rohit Beriwal", email = "r.beriwal@uq.edu.au" }
]
keywords = ["control toolbox", "timing"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "bokeh",
    "openqasm3",
    "openpulse",
    "pandas==2.3.3",
    "h5py"
]

[project.optional-dependencies]
full = [
    "qcodes>=0.21.0",
    "pyvisa-py",
    "resonator-tools",
    "ply",
    "laboneq",
    "laboneq-applications",
]

[dependency-groups]
dev = [
    "build>=1.5.0",
    "twine>=6.2.0",
]

[project.urls]
Homepage = "https://github.com/sqdlab/sqdtoolz"

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
include = ["sqdtoolz*"]

[tool.setuptools.package-data]
sqdtoolz = [
    "**/*.py",
    "**/*.inc",
]
